apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chatbot-testjul30 
  janus-idp.io/tekton: chatbot-testjul30
  backstage.io/kubernetes-id: chatbot-testjul30
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: chatbot-testjul30
resources: 
- application-dev.yaml