---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot-testjul30
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-testjul30 
  name: chatbot-testjul30
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi